name: 'Install DongTai Java Agent'
description: 'Greet someone'
inputs:
  dongtai-server:
    description: 'Whether to enable the debugging mode, the debugging mode will use the local jar package'
    required: true
    default: "https://iast.io/openapi"
  dongtai-token:
    description: 'Whether to enable the debugging mode, the debugging mode will use the local jar package'
    required: true
    default: "79798299b48839c84886d728958a8f708e119868"
  dongtai-debug:
    description: 'Whether to enable the debugging mode, the debugging mode will use the local jar package'
    required: true
    default: false
  project-name:  # id of input
    description: 'The name of the project to install DongTai'
    required: true
    default: '${{ github.repository }}'
  project-create:
    description: ''
    required: true
    default: 'true'
  project-version:
    description: ''
    required: true
    default: "${{ github.event_name }}-${{ github.run_number }}"
outputs:
  agent-env:
    description: "Agent ENV"
    value: ${{ steps.install.outputs.agent-env }}
runs:
  using: "composite"
  steps:
    - id: install
      run: ${{ github.action_path }}/install.sh
      shell: bash
      env:
        DONGTAI_SERVER: ${{ inputs.dongtai-server }}
        DONGTAI_TOKEN: ${{ inputs.dongtai-token }}
        DONGTAI_DEBUG: ${{ inputs.dongtai-debug }}
        PROJECT_NAME: ${{ inputs.project-name }}
        PROJECT_CREATE: ${{ inputs.project-create }}
        PROJECT_VERSION: ${{ inputs.project-version }}
