name: 'Install DongTai Java Agent'
description: 'Install DongTai Java Agent to .bash_profile、.bashrc'
author: "Owefsad"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  dongtai-server:
    description: 'DongTai Server Address'
    required: true
    default: "https://iast.io/openapi"
  dongtai-token:
    description: 'Auth token for DongTai Server'
    required: true
    default: "79798299b48839c84886d728958a8f708e119868"
  dongtai-debug:
    description: 'Whether to enable the debugging mode, the debugging mode will use the local jar package'
    required: true
    default: false
  project-name:
    description: 'The name of the project'
    required: true
    default: '${{ github.repository }}'
  project-create:
    description: 'Whether to automatically create a project, default: true'
    required: true
    default: 'true'
  project-version:
    description: 'The version of the project'
    required: true
    default: "${{ github.event_name }}-${{ github.run_number }}"
outputs:
  agent-env:
    description: "Agent ENV"
    value: ${{ steps.install.outputs.agent-env }}
runs:
  using: "composite"
  steps:
    - id: install
      run: ${{ github.action_path }}/install.sh
      shell: bash
      env:
        DONGTAI_SERVER: ${{ inputs.dongtai-server }}
        DONGTAI_TOKEN: ${{ inputs.dongtai-token }}
        DONGTAI_DEBUG: ${{ inputs.dongtai-debug }}
        PROJECT_NAME: ${{ inputs.project-name }}
        PROJECT_CREATE: ${{ inputs.project-create }}
        PROJECT_VERSION: ${{ inputs.project-version }}
