name: 'Install DongTai Java Agent'
description: 'Greet someone'
inputs:
  DONGTAI_SERVER:
    description: 'Whether to enable the debugging mode, the debugging mode will use the local jar package'
    required: true
    default: "https://iast.io/openapi"
  DONGTAI_TOKEN:
    description: 'Whether to enable the debugging mode, the debugging mode will use the local jar package'
    required: true
    default: "79798299b48839c84886d728958a8f708e119868"
  DONGTAI_DEBUG:
    description: 'Whether to enable the debugging mode, the debugging mode will use the local jar package'
    required: true
    default: false
  PROJECT_NAME:  # id of input
    description: 'The name of the project to install DongTai'
    required: true
    default: '${{ github.repository }}'
  PROJECT_CREATE:
    description: ''
    required: true
    default: 'true'
  PROJECT_VERSION:
    description: ''
    required: true
    default: "${{ github.event_name }}-${{ github.run_number }}"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: "echo 'start to install open-agent'"
      shell: bash
    - run: ${{ github.action_path }}/install.sh
      shell: bash
    - run: "echo 'finished. env: $JAVA_TOOL_OPTIONS"
      shell: bash
